server:
  port: 8085
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/leyou2
    password: cgl1403241032;
    username: root
  rabbitmq:
    username: leyou
    password: leyou
    virtual-host: /leyou
    host: 192.168.233.128
  redis:
    host: 192.168.233.128
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl