server:
  port: 10010
spring:
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
zuul:
  prefix: /api
  routes:
    item-service: /item/**
    search-service: /search/**
    user-service: /user/**
    auth-service: /auth/**
    cart-service: /cart/**
    upload-service:
      path: /upload/**
      serviceId: upload-service
      strip-prefix: false   #不去掉前缀，防止/upload被去掉
  add-host-header: true
  sensitive-headers:
hystrix:
  commend:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000 #熔断超时时长 5000ms
ribbon:
  ConnectTimeout: 1000 #ribbon链接超时时长
  ReadTimeout: 3500 #ribbon读取超时时长
  MaxAutoRetries: 0 #当前服务重试次数
  MaxAutoRetriesNextServer: 0 # 切换服务重试次数
ly:
  jwt:
    pubKeyPath: G:/key/rsa/rsa.pub # 公钥地址
    expire: 30 # 过期时间,单位分钟
    cookieName: "LY_TOKEN"
  filter:
    allowPaths:
      - /api/auth
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/code
      - /api/item