server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.233.128
    username: leyou
    password: leyou
    virtual-host: /leyou
  redis:
    host: 192.168.233.128
ly:
  sms:
    accessKeyId: LTAI4Ftrmg3HyvSVNhDK5eFX
    accessKeySecret: BJivqHTmZTGT7i1hjgTkyztcMAlexJ
    signName: 乐优商城
    verifyCodeTemplate: SMS_183262996
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
